/** Real titles with the nicknames people actually type, used to generate training messages. */
export interface BankTitle {
  title: string;
  kind: "movie" | "tv";
  aliases?: string[];
}

export const TITLES: BankTitle[] = [
  { title: "Severance", kind: "tv", aliases: ["sev"] },
  { title: "The Bear", kind: "tv" },
  { title: "Breaking Bad", kind: "tv", aliases: ["bb"] },
  { title: "Better Call Saul", kind: "tv", aliases: ["bcs"] },
  { title: "Game of Thrones", kind: "tv", aliases: ["got"] },
  { title: "House of the Dragon", kind: "tv", aliases: ["hotd"] },
  { title: "The Last of Us", kind: "tv", aliases: ["tlou"] },
  { title: "Stranger Things", kind: "tv", aliases: ["st"] },
  { title: "The White Lotus", kind: "tv" },
  { title: "Succession", kind: "tv" },
  { title: "Andor", kind: "tv" },
  { title: "The Mandalorian", kind: "tv", aliases: ["mando"] },
  { title: "Shōgun", kind: "tv", aliases: ["shogun"] },
  { title: "Arcane", kind: "tv" },
  { title: "Dark", kind: "tv" },
  { title: "Fleabag", kind: "tv" },
  { title: "Ted Lasso", kind: "tv" },
  { title: "The Office", kind: "tv" },
  { title: "Brooklyn Nine-Nine", kind: "tv", aliases: ["b99", "brooklyn 99"] },
  { title: "Peaky Blinders", kind: "tv" },
  { title: "The Crown", kind: "tv" },
  { title: "Squid Game", kind: "tv" },
  { title: "Wednesday", kind: "tv" },
  { title: "The Boys", kind: "tv" },
  { title: "Fallout", kind: "tv" },
  { title: "Slow Horses", kind: "tv" },
  { title: "Reacher", kind: "tv" },
  { title: "Mirzapur", kind: "tv" },
  { title: "Panchayat", kind: "tv" },
  { title: "Sacred Games", kind: "tv" },
  { title: "Scam 1992", kind: "tv" },
  { title: "Kota Factory", kind: "tv" },
  { title: "The Family Man", kind: "tv" },
  { title: "Money Heist", kind: "tv", aliases: ["la casa de papel"] },
  { title: "Friends", kind: "tv" },
  { title: "The Sopranos", kind: "tv" },
  { title: "The Wire", kind: "tv" },
  { title: "True Detective", kind: "tv" },
  { title: "Mr. Robot", kind: "tv", aliases: ["mr robot"] },
  { title: "Black Mirror", kind: "tv" },
  { title: "The Penguin", kind: "tv" },
  { title: "Only Murders in the Building", kind: "tv", aliases: ["omitb"] },
  { title: "Abbott Elementary", kind: "tv" },
  { title: "Baby Reindeer", kind: "tv" },
  { title: "Ripley", kind: "tv" },
  { title: "Oppenheimer", kind: "movie" },
  { title: "Barbie", kind: "movie" },
  { title: "Interstellar", kind: "movie" },
  { title: "Inception", kind: "movie" },
  { title: "The Dark Knight", kind: "movie", aliases: ["tdk"] },
  { title: "Dune", kind: "movie" },
  { title: "Dune: Part Two", kind: "movie", aliases: ["dune 2", "dune part 2"] },
  { title: "Arrival", kind: "movie" },
  { title: "Blade Runner 2049", kind: "movie", aliases: ["br2049"] },
  { title: "Parasite", kind: "movie" },
  { title: "Past Lives", kind: "movie" },
  { title: "Everything Everywhere All at Once", kind: "movie", aliases: ["eeaao"] },
  { title: "Poor Things", kind: "movie" },
  { title: "The Substance", kind: "movie" },
  { title: "Anatomy of a Fall", kind: "movie" },
  {
    title: "Spider-Man: Across the Spider-Verse",
    kind: "movie",
    aliases: ["across the spiderverse", "spiderverse 2"],
  },
  { title: "Top Gun: Maverick", kind: "movie", aliases: ["top gun 2", "maverick"] },
  { title: "Mad Max: Fury Road", kind: "movie", aliases: ["fury road"] },
  { title: "The Godfather", kind: "movie" },
  { title: "Pulp Fiction", kind: "movie" },
  { title: "Fight Club", kind: "movie" },
  { title: "The Shawshank Redemption", kind: "movie", aliases: ["shawshank"] },
  { title: "Whiplash", kind: "movie" },
  { title: "La La Land", kind: "movie" },
  { title: "Get Out", kind: "movie" },
  { title: "Hereditary", kind: "movie" },
  { title: "The Social Network", kind: "movie" },
  { title: "Spirited Away", kind: "movie" },
  { title: "Your Name", kind: "movie" },
  { title: "Oldboy", kind: "movie" },
  { title: "Amélie", kind: "movie", aliases: ["amelie"] },
  { title: "3 Idiots", kind: "movie" },
  { title: "Dangal", kind: "movie" },
  { title: "RRR", kind: "movie" },
  { title: "Lagaan", kind: "movie" },
  { title: "Zindagi Na Milegi Dobara", kind: "movie", aliases: ["znmd"] },
  { title: "Gangs of Wasseypur", kind: "movie", aliases: ["gow"] },
  { title: "Andhadhun", kind: "movie" },
  { title: "Jawan", kind: "movie" },
  { title: "Kantara", kind: "movie" },
  { title: "Drishyam", kind: "movie" },
  { title: "The Matrix", kind: "movie" },
  { title: "Avengers: Endgame", kind: "movie", aliases: ["endgame"] },
  { title: "Joker", kind: "movie" },
  { title: "Gladiator II", kind: "movie", aliases: ["gladiator 2"] },
  { title: "Wicked", kind: "movie" },
  { title: "Conclave", kind: "movie" },
  { title: "The Brutalist", kind: "movie" },
  { title: "Challengers", kind: "movie" },
  { title: "Inside Out 2", kind: "movie" },
  { title: "Deadpool & Wolverine", kind: "movie", aliases: ["deadpool 3"] },
  { title: "The Holdovers", kind: "movie" },
  { title: "Killers of the Flower Moon", kind: "movie" },
  { title: "No Country for Old Men", kind: "movie" },
  { title: "The Grand Budapest Hotel", kind: "movie", aliases: ["grand budapest"] },
  { title: "Prisoners", kind: "movie" },
  { title: "Sicario", kind: "movie" },
  { title: "Her", kind: "movie" },
  { title: "Before Sunrise", kind: "movie" },
  { title: "Mean Girls", kind: "movie" },
];
